version: '3'

services:
  postgresql:
    container_name: postgres
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - global-pg-data:/var/lib/postgresql/data

volumes:
  global-pg-data:
